# Generated by Django 4.1.2 on 2022-10-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_projeto_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='foto_projeto',
            field=models.ImageField(blank=True, upload_to='foto/%d/%m/%Y'),
        ),
    ]
